### ISSUE TITLE
Why are destructor calls is swap() commented out?

### ISSUE THREAD

**Issue by sorin-manole** [martinmoene/expected-dark#17]
https://github.com/martinmoene/expected-lite/blob/master/include/nonstd/expected.hpp#L637

**Comment by martinmoene** [comment]
Good question; I can't remember why I put it that way.  
It looks like they just must be activated. Will look at it later.

**Comment by sorin-manole** [comment]
If it helps, it looks like Alexandrescu makes the same “mistake” in his
slides.

**Comment by martinmoene** [comment]
Fixed in 1e37bb075e57c6d3b0cfcccfd400b8999476b175
