### ISSUE TITLE
What's the cost of expected-lite vs an exception?

### ISSUE THREAD

**Issue by ruipacheco** [martinmoene/expected-dark#2]
Is expected-lite much more expensive than using exceptions? It's very practical and would lead to significantly cleaner code than exception handling but what is the runtime cost?

**Comment by ruipacheco** [comment]
Bump

**Comment by martinmoene** [comment]
I have not investigated it. The answer likely is: it depends -- on the specifics of how/where you use it.

Would be nice if you could shed some light on it !

**Comment by martinmoene** [comment]
@ruipacheco At the [ACCU 2017 Conference](https://conference.accu.org/site/), [Niall Douglas](https://conference.accu.org/site/stories/2017/presenters.html#XNiall_Douglas) did a talk on [`std::expected`](http://wg21.link/p0323):

[Mongrel Monads, Dirty, Dirty, Dirty - Niall Douglas [ACCU 2017] ](https://youtu.be/XVofgKH-uu4)

57 minutes in is a section [Benchmarking performance; Why not just throw exception and save all this hassle?](https://youtu.be/XVofgKH-uu4?t=57m)

[Tutorial text and code as in video](https://ned14.github.io/boost.outcome/md_doc_md_02-tutorial_a.html) (Github repo for [Boost.Outcome](https://github.com/ned14/boost.outcome)).

**Comment by ruipacheco** [comment]
Will check it asap.
