### ISSUE TITLE
expected::operator*() for rvalue types should not be const

### ISSUE THREAD

**Issue by rnburn** [martinmoene/expected-dark#24]
See https://github.com/opentracing/opentracing-cpp/issues/64

**Comment by martinmoene** [comment]
Thanks Ryan,

It looks like 
```
constexpr value_type const && operator *() const &&
```
is missing, and 
```
constexpr value_type && operator *() const &&
```
is a mixture of both `&&` methods.

You may have noticed I'm in the process of updating expected-lite for proposal p0323r5 in issue #20 where it hopefully also would have surfaced.

**Comment by rnburn** [comment]
Shouldn't there be a
```
 value_type && operator *() &&
```

**Comment by martinmoene** [comment]
Yes. Sorry to be have been too implicit, but that's what I also meant.
