### ISSUE TITLE
Replace default error type std::exception_ptr with std::error_code

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/expected-dark#5]
Per [Boost.Outcome](https://github.com/ned14/boost.outcome) and likely [`std::expected`](http://wg21.link/p0323).

[Boost.Outcome vs std::expected](https://github.com/ned14/outcome/blob/master/doc/md/attic/std_expected.md) ([old](https://ned14.github.io/boost.outcome/md_doc_md_08-expectedsynopsis.html)).

**Comment by rnburn** [comment]
Would you be open to accepting a PR for this? Or is it still something that's being considered?

**Comment by martinmoene** [comment]
Thanks for your offer.

The consideration is/was to follow what comes out from [`std::expected`](http://wg21.link/p0323).

P0323R2 (2017-06-15):
>What about changing the default Error argument to error_code?
>Niall has suggested that std::error_code is a better default for the expected Error parameter.

Seems this has not been decided yet.

**Comment by viboes** [comment]
The last decision was to don't have a default :), but who know what will be in the standard version.

You can take a look at the last draft that I should send for the next meeting (wording to be polished yet).

https://github.com/viboes/std-make/blob/master/doc/proposal/expected/d0323r3.md#history

**Comment by martinmoene** [comment]
I'm in the process of updating _expected-lite_ to [p0323r5](http://wg21.link/p0323).

As Vicente noted, a/the default error type has disappeared from the proposal, so I'll remove it too. 

For now I'll try to provide (some) backwards compatibility via `-Dndel_P0323R=N`, however, it's void of any guarantee.

I'll close the issue.
